DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "Movies" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Title" NVARCHAR2(200) NOT NULL,
        "Description" NVARCHAR2(1000),
        "Director" NVARCHAR2(100),
        "Cast" NVARCHAR2(500),
        "Genre" NVARCHAR2(100),
        "DurationMinutes" NUMBER(10),
        "Language" NVARCHAR2(50),
        "RatingCode" NVARCHAR2(10),
        "PosterUrl" NVARCHAR2(2000),
        "TrailerUrl" NVARCHAR2(2000),
        "ReleaseDate" DATE,
        "EndDate" DATE,
        "IsActive" BOOLEAN DEFAULT True NOT NULL,
        "CreatedAt" DATE NOT NULL,
        "UpdatedAt" DATE,
        CONSTRAINT "PK_Movies" PRIMARY KEY ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "Showtimes" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "MovieId" NUMBER(10) NOT NULL,
        "RoomNumber" NVARCHAR2(10) NOT NULL,
        "StartTime" DATE NOT NULL,
        "EndTime" DATE NOT NULL,
        "BasePrice" DECIMAL(10,2) NOT NULL,
        "TotalSeats" NUMBER(10) NOT NULL,
        "BookedSeatsCount" NUMBER(10) DEFAULT 0 NOT NULL,
        "IsActive" BOOLEAN DEFAULT True NOT NULL,
        "CreatedAt" DATE NOT NULL,
        "UpdatedAt" DATE,
        CONSTRAINT "PK_Showtimes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Showtimes_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "Bookings" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "BookingCode" NVARCHAR2(30) NOT NULL,
        "ShowtimeId" NUMBER(10) NOT NULL,
        "CustomerId" NUMBER(10),
        "Status" NUMBER(10) DEFAULT 0 NOT NULL,
        "TotalTickets" NUMBER(10) NOT NULL,
        "SubTotal" DECIMAL(15,2) NOT NULL,
        "DiscountAmount" DECIMAL(15,2) DEFAULT 0.0 NOT NULL,
        "TotalAmount" DECIMAL(15,2) NOT NULL,
        "PromotionCode" NVARCHAR2(50),
        "SessionId" NVARCHAR2(100),
        "BookedAt" DATE NOT NULL,
        "ExpiresAt" DATE,
        "PaidAt" DATE,
        "PaymentMethod" NVARCHAR2(20),
        "TransactionId" NVARCHAR2(100),
        "Notes" NVARCHAR2(500),
        "UpdatedAt" DATE,
        CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Bookings_Showtimes_ShowtimeId" FOREIGN KEY ("ShowtimeId") REFERENCES "Showtimes" ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "ShowtimeSeats" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "ShowtimeId" NUMBER(10) NOT NULL,
        "SeatNumber" NVARCHAR2(10) NOT NULL,
        "RowLetter" NVARCHAR2(5) NOT NULL,
        "ColumnNumber" NUMBER(10) NOT NULL,
        "Status" NUMBER(10) DEFAULT 0 NOT NULL,
        "LockedAt" DATE,
        "LockedBySessionId" NVARCHAR2(100),
        "BookedByUserId" NUMBER(10),
        "TicketId" NUMBER(10),
        "CreatedAt" DATE NOT NULL,
        "UpdatedAt" DATE,
        CONSTRAINT "PK_ShowtimeSeats" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ShowtimeSeats_Showtimes_ShowtimeId" FOREIGN KEY ("ShowtimeId") REFERENCES "Showtimes" ("Id") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "Tickets" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "TicketCode" NVARCHAR2(30) NOT NULL,
        "BookingId" NUMBER(10) NOT NULL,
        "ShowtimeSeatId" NUMBER(10) NOT NULL,
        "Price" DECIMAL(10,2) NOT NULL,
        "SeatType" NVARCHAR2(20) DEFAULT N''STANDARD'',
        "IsActive" BOOLEAN DEFAULT True NOT NULL,
        "IssuedAt" DATE NOT NULL,
        "UsedAt" DATE,
        "PrintCount" NUMBER(10) DEFAULT 0 NOT NULL,
        "LastPrintedAt" DATE,
        "Notes" NVARCHAR2(500),
        "CreatedAt" DATE DEFAULT TO_DATE(''2026-04-15 16:06:42'', ''YYYY-MM-DD HH24:MI:SS'') NOT NULL,
        "UpdatedAt" DATE,
        CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tickets_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tickets_ShowtimeSeats_ShowtimeSeatId" FOREIGN KEY ("ShowtimeSeatId") REFERENCES "ShowtimeSeats" ("Id")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_Booking_ExpiresAt" ON "Bookings" ("ExpiresAt")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_Booking_ShowtimeId" ON "Bookings" ("ShowtimeId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_Booking_ShowtimeId_Status" ON "Bookings" ("ShowtimeId", "Status")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_Booking_Status" ON "Bookings" ("Status")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "UX_Booking_BookingCode" ON "Bookings" ("BookingCode")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_Showtime_MovieId" ON "Showtimes" ("MovieId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_Showtime_StartTime_IsActive" ON "Showtimes" ("StartTime", "IsActive")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_ShowtimeSeat_LockedAt" ON "ShowtimeSeats" ("LockedAt")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_ShowtimeSeat_LockedBySessionId" ON "ShowtimeSeats" ("LockedBySessionId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_ShowtimeSeat_ShowtimeId_Status" ON "ShowtimeSeats" ("ShowtimeId", "Status")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "UX_ShowtimeSeat_ShowtimeId_SeatNumber" ON "ShowtimeSeats" ("ShowtimeId", "SeatNumber")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_Ticket_BookingId" ON "Tickets" ("BookingId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "IX_Ticket_ShowtimeSeatId" ON "Tickets" ("ShowtimeSeatId")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE INDEX "IX_Ticket_UsedAt" ON "Tickets" ("UsedAt")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'CREATE UNIQUE INDEX "UX_Ticket_TicketCode" ON "Tickets" ("TicketCode")'
    ;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260415160643_InitialCreate';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE 
    'INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (N''20260415160643_InitialCreate'', N''10.0.6'')'
    ;
 END IF;
END;

/

