// <auto-generated />
using System;
using CinemaBooking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CinemaBooking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426205253_AddMovieStatus")]
    partial class AddMovieStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("BookedAt");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("BookingCode");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CustomerId");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("DECIMAL(15,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("DiscountAmount");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("DATE")
                        .HasColumnName("ExpiresAt");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("Notes");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("DATE")
                        .HasColumnName("PaidAt");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PaymentMethod");

                    b.Property<string>("PromotionCode")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("PromotionCode");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SessionId");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ShowtimeId");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TotalTickets");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TransactionId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Booking_BookingCode");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Booking_ExpiresAt");

                    b.HasIndex("ShowtimeId")
                        .HasDatabaseName("IX_Booking_ShowtimeId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Booking_Status");

                    b.HasIndex("ShowtimeId", "Status")
                        .HasDatabaseName("IX_Booking_ShowtimeId_Status");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerUrl")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("BannerUrl");

                    b.Property<string>("Cast")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("Cast");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("Director");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DurationMinutes");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("EndDate");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("Genre");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsFeatured");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("Language");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PosterUrl");

                    b.Property<string>("RatingCode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("RatingCode");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("DATE")
                        .HasColumnName("ReleaseDate");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("Title");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TrailerUrl");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("Name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Name = "Phòng 01",
                            Type = "2D"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            Name = "Phòng 02",
                            Type = "3D"
                        });
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.SeatTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DisplayOrder");

                    b.Property<int>("Number")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Number");

                    b.Property<int>("RoomId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RoomId");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)")
                        .HasColumnName("Row");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("IX_SeatTemplate_RoomId");

                    b.HasIndex("RoomId", "Row", "Number")
                        .IsUnique()
                        .HasDatabaseName("UX_SeatTemplate_RoomId_Row_Number");

                    b.ToTable("SeatTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Number = 1,
                            RoomId = 1,
                            Row = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Number = 2,
                            RoomId = 1,
                            Row = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Number = 3,
                            RoomId = 1,
                            Row = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Number = 4,
                            RoomId = 1,
                            Row = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Number = 5,
                            RoomId = 1,
                            Row = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Number = 1,
                            RoomId = 1,
                            Row = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Number = 2,
                            RoomId = 1,
                            Row = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Number = 3,
                            RoomId = 1,
                            Row = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Number = 4,
                            RoomId = 1,
                            Row = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Number = 5,
                            RoomId = 1,
                            Row = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Number = 1,
                            RoomId = 1,
                            Row = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Number = 2,
                            RoomId = 1,
                            Row = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Number = 3,
                            RoomId = 1,
                            Row = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Number = 4,
                            RoomId = 1,
                            Row = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            Number = 5,
                            RoomId = 1,
                            Row = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            Number = 1,
                            RoomId = 1,
                            Row = "D",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            Number = 2,
                            RoomId = 1,
                            Row = "D",
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            Number = 3,
                            RoomId = 1,
                            Row = "D",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            Number = 4,
                            RoomId = 1,
                            Row = "D",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 20,
                            Number = 5,
                            RoomId = 1,
                            Row = "D",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 1,
                            Number = 1,
                            RoomId = 2,
                            Row = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 2,
                            Number = 2,
                            RoomId = 2,
                            Row = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 3,
                            Number = 3,
                            RoomId = 2,
                            Row = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 4,
                            Number = 4,
                            RoomId = 2,
                            Row = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 5,
                            Number = 5,
                            RoomId = 2,
                            Row = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 6,
                            Number = 1,
                            RoomId = 2,
                            Row = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 7,
                            Number = 2,
                            RoomId = 2,
                            Row = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 8,
                            Number = 3,
                            RoomId = 2,
                            Row = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 9,
                            Number = 4,
                            RoomId = 2,
                            Row = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 10,
                            Number = 5,
                            RoomId = 2,
                            Row = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 11,
                            Number = 1,
                            RoomId = 2,
                            Row = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 12,
                            Number = 2,
                            RoomId = 2,
                            Row = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 13,
                            Number = 3,
                            RoomId = 2,
                            Row = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 14,
                            Number = 4,
                            RoomId = 2,
                            Row = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 15,
                            Number = 5,
                            RoomId = 2,
                            Row = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 16,
                            Number = 1,
                            RoomId = 2,
                            Row = "D",
                            Type = 1
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 17,
                            Number = 2,
                            RoomId = 2,
                            Row = "D",
                            Type = 1
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 18,
                            Number = 3,
                            RoomId = 2,
                            Row = "D",
                            Type = 1
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 19,
                            Number = 4,
                            RoomId = 2,
                            Row = "D",
                            Type = 1
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 20,
                            Number = 5,
                            RoomId = 2,
                            Row = "D",
                            Type = 1
                        });
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("BasePrice");

                    b.Property<int>("BookedSeatsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("BookedSeatsCount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("DATE")
                        .HasColumnName("EndTime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<int>("MovieId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MovieId");

                    b.Property<int>("RoomId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RoomId");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("DATE")
                        .HasColumnName("StartTime");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TotalSeats");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("IX_Showtime_MovieId");

                    b.HasIndex("RoomId");

                    b.HasIndex("StartTime", "IsActive")
                        .HasDatabaseName("IX_Showtime_StartTime_IsActive");

                    b.ToTable("Showtimes", (string)null);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.ShowtimeSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookedByUserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BookedByUserId");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ColumnNumber");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("HoldExpiryTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("LockedAt");

                    b.Property<string>("LockedBySessionId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LockedBySessionId");

                    b.Property<string>("RowLetter")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)")
                        .HasColumnName("RowLetter");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("SeatNumber");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ShowtimeId");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<int?>("TicketId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TicketId");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("LockedAt")
                        .HasDatabaseName("IX_ShowtimeSeat_LockedAt");

                    b.HasIndex("LockedBySessionId")
                        .HasDatabaseName("IX_ShowtimeSeat_LockedBySessionId");

                    b.HasIndex("ShowtimeId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ShowtimeSeat_ShowtimeId_SeatNumber");

                    b.HasIndex("ShowtimeId", "Status")
                        .HasDatabaseName("IX_ShowtimeSeat_ShowtimeId_Status");

                    b.ToTable("ShowtimeSeats", (string)null);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BookingId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("IssuedAt");

                    b.Property<DateTime?>("LastPrintedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("LastPrintedAt");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("Notes");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("Price");

                    b.Property<int>("PrintCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("PrintCount");

                    b.Property<string>("SeatType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("STANDARD")
                        .HasColumnName("SeatType");

                    b.Property<int>("ShowtimeSeatId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ShowtimeSeatId");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TicketCode");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("UpdatedAt");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("UsedAt");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_Ticket_BookingId");

                    b.HasIndex("ShowtimeSeatId")
                        .IsUnique()
                        .HasDatabaseName("IX_Ticket_ShowtimeSeatId");

                    b.HasIndex("TicketCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Ticket_TicketCode");

                    b.HasIndex("UsedAt")
                        .HasDatabaseName("IX_Ticket_UsedAt");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("FullName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsEmailConfirmed");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("DATE")
                        .HasColumnName("LastLogin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("Role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_User_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_User_IsActive");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.User", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CinemaBooking.Domain.Entities.Showtime", "Showtime")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.SeatTemplate", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Room", "Room")
                        .WithMany("SeatTemplates")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Showtime", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBooking.Domain.Entities.Room", "Room")
                        .WithMany("Showtimes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.ShowtimeSeat", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Showtime", "Showtime")
                        .WithMany("Seats")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBooking.Domain.Entities.ShowtimeSeat", "ShowtimeSeat")
                        .WithOne("Ticket")
                        .HasForeignKey("CinemaBooking.Domain.Entities.Ticket", "ShowtimeSeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ShowtimeSeat");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Movie", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Room", b =>
                {
                    b.Navigation("SeatTemplates");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Showtime", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.ShowtimeSeat", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
